--- #YAML:1.0
name:                Gnome2-PanelApplet
version:             0.02
abstract:            Perl interface to GNOME's applet library
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    ExtUtils::Depends:             0.20
    ExtUtils::PkgConfig:           1.03
    Glib:                          1.160
    Gnome2:                        1.042
    Gnome2::GConf:                 1.044
    Gtk2:                          1.040
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
